name: Release Action

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: composite
  steps:
    - name: Set Node version
      uses: actions/setup-node@v3
      with:
        node-version: 17
    - name: Install dependencies
      shell: bash
      run: npm ci
    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
      run: npx semantic-release
