name: Test Release Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Release
      uses: chiemerieezechukwu/semantic-release@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}